spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jobmarket
    username: jobmarket
    password: jobmarket123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

scheduler:
  job-count:
    enabled: false
